#!/usr/bin/env node
/**
 * Keep the published API surface in docs/reference.md, and fail if
 * hand-written docs drift from source.
 *
 *   node scripts/docs.mjs write
 *   node scripts/docs.mjs check
 *   node scripts/docs.mjs json
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const root = process.env.HYPERPAY_ROOT ?? join(scriptDir, '..')
const referencePath = process.env.HYPERPAY_DOCS_OUT ?? join(root, 'docs/reference.md')

const BANNER =
  '<!-- Generated by `node scripts/docs.mjs write`. Do not edit. Run `just docs` after changing public APIs. -->'

const HAND_WRITTEN = [
  'README.md',
  'AGENTS.md',
  'examples/ai-skill/SKILL.md',
  'packages/hyperpay/README.md',
  'packages/core/README.md',
  'packages/types/README.md',
  'packages/solana/README.md',
  'packages/x402/README.md',
  'packages/react/README.md',
  'crates/hyperpay/README.md',
  '.env.example',
]

function read(rel) {
  return readFileSync(join(root, rel), 'utf8')
}

function tryRead(rel) {
  const path = join(root, rel)
  return existsSync(path) ? readFileSync(path, 'utf8') : ''
}

function unique(items) {
  return [...new Set(items)]
}

function sorted(items) {
  return [...items].sort((a, b) => a.localeCompare(b))
}

function extractAll(regex, text, group = 1) {
  const out = []
  regex.lastIndex = 0
  let match
  while ((match = regex.exec(text))) out.push(match[group])
  return out
}

function extractProgramId(text) {
  return (
    /declare_id!\("([^"]+)"\)/.exec(text)?.[1] ??
    /PROGRAM_ID = new PublicKey\('([^']+)'\)/.exec(text)?.[1] ??
    /pub const PROGRAM_ID: Pubkey = solana_sdk::pubkey!\("([^"]+)"\)/.exec(text)?.[1]
  )
}

function extractHyperPayMethods(src) {
  const start = src.indexOf('export class HyperPay {')
  if (start < 0) return []
  const body = src.slice(start)
  const re =
    /^(  \/\*\*[\s\S]*?\*\/\n)?  (static )?(async )?([a-zA-Z]\w*)\(/gm
  const found = []
  let match
  while ((match = re.exec(body))) {
    found.push({
      index: match.index,
      docs: (match[1] ?? '')
        .replace(/^\s*\/\*\*\s*/, '')
        .replace(/\s*\*\/\s*$/, '')
        .replace(/^\s*\* ?/gm, '')
        .trim()
        .split(/\n\n/)[0]
        .replace(/\s+/g, ' '),
      name: match[4],
      static: Boolean(match[2]),
      async: Boolean(match[3]),
    })
  }
  return found.map((method, i) => {
    const slice = body.slice(method.index, found[i + 1]?.index ?? body.length)
    const usesEphemeral = slice.includes('this.ephemeralRpcUrl')
    const usesBase = slice.includes('this.rpcUrl')
    let lands = 'local'
    if (usesEphemeral && usesBase) lands = 'base + ephemeral'
    else if (usesEphemeral) lands = 'ephemeral'
    else if (usesBase) lands = 'base'
    return { name: method.name, docs: method.docs, lands, static: method.static, async: method.async }
  })
}

function extractRustHyperPayMethods(src) {
  const start = src.indexOf('impl HyperPay {')
  if (start < 0) return []
  const body = src.slice(start)
  return unique(
    extractAll(/^\s+pub (?:async )?fn ([a-z0-9_]+)/gm, body),
  )
}

function extractNamedExports(src) {
  const names = []
  for (const block of extractAll(/export \{([^}]+)\}/g, src)) {
    for (const part of block.split(',')) {
      const name = part.trim().split(/\s+as\s+/).at(-1)?.split(/\s+/)[0]
      if (name) names.push(name)
    }
  }
  names.push(
    ...extractAll(/^export (?:async )?function (\w+)/gm, src),
    ...extractAll(/^export class (\w+)/gm, src),
    ...extractAll(/^export const (\w+)/gm, src),
    ...extractAll(/^export interface (\w+)/gm, src),
    ...extractAll(/^export type \{([^}]+)\}/gm, src).flatMap((block) =>
      block.split(',').map((part) => part.trim().split(/\s+as\s+/).at(-1)?.split(/\s+/)[0]).filter(Boolean),
    ),
  )
  return sorted(unique(names))
}

function extractEnvVars(text) {
  return unique(extractAll(/\b(HYPERPAY_[A-Z0-9_]+)\b/g, text))
}

function npmPackages() {
  const dir = join(root, 'packages')
  if (!existsSync(dir)) return []
  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const path = join(dir, entry.name, 'package.json')
      if (!existsSync(path)) return null
      const pkg = JSON.parse(readFileSync(path, 'utf8'))
      return {
        dir: `packages/${entry.name}`,
        name: pkg.name,
        description: pkg.description ?? '',
      }
    })
    .filter(Boolean)
}

function extract() {
  const programSrc = tryRead('programs/hyperpay/src/lib.rs')
  const stateSrc = tryRead('programs/hyperpay/src/state.rs')
  const errorSrc = tryRead('programs/hyperpay/src/errors.rs')
  const tsProgram = tryRead('packages/core/src/program.ts')
  const rsProgram = tryRead('crates/hyperpay/src/program.rs')
  const clientSrc = tryRead('packages/core/src/client.ts')
  const policySrc = tryRead('packages/core/src/policy.ts')
  const cliSrc = tryRead('packages/hyperpay/src/cli.ts')
  const mcpSrc = tryRead('packages/hyperpay/src/mcp.ts')
  const errorsTs = tryRead('packages/types/src/errors.ts')
  const rustClient = tryRead('crates/hyperpay/src/client.rs')
  const rustPolicy = tryRead('crates/hyperpay/src/policy.rs')
  const rustExample = tryRead('crates/hyperpay/examples/pay.rs')
  const envExample = tryRead('.env.example')
  const x402Src = tryRead('packages/x402/src/index.ts')
  const reactSrc = tryRead('packages/react/src/index.ts')

  const programIds = {
    'programs/hyperpay/src/lib.rs': extractProgramId(programSrc),
    'packages/core/src/program.ts': extractProgramId(tsProgram),
    'crates/hyperpay/src/program.rs': extractProgramId(rsProgram),
  }

  const helpCommands = extractAll(/^\s+hyperpay ([a-z0-9-]+) /gm, cliSrc)
  const switchCommands = extractAll(/^\s+case '([a-z0-9-]+)':/gm, cliSrc)
  if (/command === 'mcp'/.test(cliSrc) && !switchCommands.includes('mcp')) {
    switchCommands.push('mcp')
  }

  const fromEnvVars = sorted(
    unique([
      ...extractEnvVars(clientSrc),
      ...extractEnvVars(policySrc),
      ...extractEnvVars(rustClient),
      ...extractEnvVars(rustPolicy),
    ]),
  )
  const extraEnvVars = sorted(
    unique(extractEnvVars(rustExample)).filter((name) => !fromEnvVars.includes(name)),
  )

  return {
    programId: programIds['programs/hyperpay/src/lib.rs'],
    programIds,
    instructions: extractAll(/^\s{4}pub fn ([a-z0-9_]+)/gm, programSrc),
    accounts: extractAll(/^pub struct (\w+)/gm, stateSrc),
    programErrors: extractAll(/^\s{4}(\w+),$/gm, errorSrc),
    tsMethods: extractHyperPayMethods(clientSrc),
    rustMethods: extractRustHyperPayMethods(rustClient),
    cliCommands: sorted(unique([...helpCommands, ...switchCommands])),
    helpCommands: sorted(unique(helpCommands)),
    switchCommands: sorted(unique(switchCommands)),
    mcpTools: extractAll(/registerTool\(\s*'([a-z0-9_]+)'/g, mcpSrc),
    sdkErrors: extractAll(/^export class (\w+)/gm, errorsTs),
    fromEnvVars,
    extraEnvVars,
    envExampleVars: sorted(unique(extractEnvVars(envExample))),
    packages: npmPackages(),
    x402Exports: extractNamedExports(x402Src),
    reactExports: extractNamedExports(reactSrc),
  }
}

function methodRow(method) {
  const flags = [method.static ? 'static' : '', method.async ? 'async' : ''].filter(Boolean).join(', ')
  const note = [flags, method.lands, method.docs].filter(Boolean).join(' — ')
  return `| \`${method.name}\` | ${note} |`
}

function bullet(items) {
  return items.map((item) => `- \`${item}\``).join('\n')
}

function generate(surface) {
  const tsMethods = surface.tsMethods.filter((method) => method.name !== 'constructor')
  const tsNames = tsMethods.map((m) => m.name)
  const programAsCamel = surface.instructions.map((name) =>
    name.replace(/_([a-z])/g, (_, c) => c.toUpperCase()),
  )
  const sdkOnly = tsNames.filter((name) => !programAsCamel.includes(name))

  return `${BANNER}

# HyperPay reference

Generated from source. Intro: [README.md](../README.md). Agent map: [AGENTS.md](../AGENTS.md).

The SDK builds, signs, and submits the hyperpay program. There is no hosted payments API.

## Program

- Id: \`${surface.programId}\`
- Source: [\`programs/hyperpay\`](../programs/hyperpay)

### Instructions

${bullet(surface.instructions)}

\`ping\` is a health check. \`ensure_user_mint\` is used by \`topUp\`, not as a standalone SDK method.

### Accounts

${bullet(surface.accounts)}

\`User.authority\` is the wallet. Tokens sit in an eSPL eATA owned by the User PDA. \`UserMint.reserved\` plus \`Session.remaining\` isolate merchants.

### Errors

${bullet(surface.programErrors)}

## TypeScript \`HyperPay\`

Source: [\`packages/core/src/client.ts\`](../packages/core/src/client.ts)

| Method | Notes |
|---|---|
${tsMethods.map(methodRow).join('\n')}

SDK-only (not 1:1 program instructions): ${sdkOnly.map((n) => `\`${n}\``).join(', ')}.

Typical flow: \`initUser\` → \`delegateUser\` → \`topUp\` → \`openSession(merchant, amount)\` → merchant \`charge\` → \`closeSession\` → \`withdraw\`.

\`fromEnv()\` and \`{ key }\` are Node-only. In the browser, pass \`{ signer }\`. When the signer is a session key, pass \`authority\` (the wallet that owns the User PDA). Never pass a user's session token to a merchant \`charge\`.

## Rust \`hyperpay::HyperPay\`

Source: [\`crates/hyperpay/src/client.rs\`](../crates/hyperpay/src/client.rs)

${bullet(surface.rustMethods)}

Same client. \`cargo run -p hyperpay --example pay\` is the script form. Session keys: \`HYPERPAY_AUTHORITY\` or \`SessionOpts { authority: Some(wallet), .. }\`.

## CLI

Binary: \`hyperpay\` (\`npx @magicblock-labs/hyperpay\`; never bare \`npx hyperpay\`).

${bullet(surface.cliCommands)}

Flags: \`--token\`, \`--authority\`, \`--destination\`, \`--cluster\`, \`--address\`, \`--yes\`/\`-y\`, \`--json\`.

## MCP

\`npx @magicblock-labs/hyperpay mcp\` (stdio). Call \`policy\` first.

${bullet(surface.mcpTools)}

## Environment

Read by \`HyperPay.fromEnv\` / \`Policy.fromEnv\`:

${bullet(surface.fromEnvVars)}

Rust example only:

${bullet(surface.extraEnvVars)}

Caps fail closed: a USDC cap refuses a USDT payment. Deny is checked before allow. Daily spend journals to \`HYPERPAY_JOURNAL\` (default \`~/.hyperpay/spend.json\`).

## SDK errors

All extend \`HyperPayError\`. \`PolicyError\` means nothing was signed.

${bullet(surface.sdkErrors)}

There is no \`pay()\`, \`InsufficientFundsError\`, \`HYPERPAY_API\`, or hosted Payments API.

## Packages

| Package | Path |
|---|---|
${surface.packages.map((pkg) => `| \`${pkg.name}\` | [\`${pkg.dir}\`](../${pkg.dir}) |`).join('\n')}

Prefer a focused package for tree-shaking. React is a separate install; the umbrella does not depend on it. \`memoryJournal\` / \`fileJournal\` live on \`@magicblock-labs/hyperpay-core\` (or \`@magicblock-labs/hyperpay/core\`).

## x402

${bullet(surface.x402Exports)}

The user must \`openSession\` before the merchant can \`charge\`. There is no transfer-API fallback.

## React

Install \`@magicblock-labs/hyperpay-react\` separately.

${bullet(surface.reactExports)}

\`PayButton\` calls \`openSession\`. \`fromEnv()\` / \`{ key }\` are Node-only; pass \`wallet\` or \`signer\`.
`
}

function problemsFor(surface, markdown) {
  const problems = []
  const ids = Object.entries(surface.programIds)
  const expected = surface.programId
  if (!expected) problems.push('could not read program id from programs/hyperpay/src/lib.rs')
  for (const [path, id] of ids) {
    if (!id) problems.push(`could not read program id from ${path}`)
    else if (expected && id !== expected) {
      problems.push(`${path} program id is ${id}, expected ${expected}`)
    }
  }

  const help = surface.helpCommands.join(',')
  const sw = surface.switchCommands.join(',')
  if (help !== sw) {
    problems.push(`CLI HELP commands [${surface.helpCommands.join(', ')}] != switch [${surface.switchCommands.join(', ')}]`)
  }

  const missingEnv = surface.fromEnvVars.filter((name) => !surface.envExampleVars.includes(name))
  if (missingEnv.length) {
    problems.push(`.env.example is missing ${missingEnv.join(', ')}`)
  }

  const cliHelp = tryRead('packages/hyperpay/src/cli.ts')
  const missingInHelp = surface.fromEnvVars.filter((name) => !cliHelp.includes(name))
  if (missingInHelp.length) {
    problems.push(`CLI HELP is missing ${missingInHelp.join(', ')}`)
  }

  if (markdown.trim() !== generate(surface).trim()) {
    problems.push(`${relative(root, referencePath) || 'docs/reference.md'} is stale — run \`just docs\``)
  }

  const required = {
    'README.md': [
      expected,
      'AGENTS.md',
      'docs/reference.md',
      ...surface.packages.map((pkg) => pkg.name),
      ...surface.sdkErrors,
    ],
    'AGENTS.md': [
      expected,
      'just docs',
      'programs/hyperpay',
      'packages/core',
      'openSession',
      'charge',
      'pay()',
      'HYPERPAY_API',
      'InsufficientFundsError',
    ],
    'examples/ai-skill/SKILL.md': [expected, ...surface.mcpTools, 'PolicyError'],
  }

  for (const [file, needles] of Object.entries(required)) {
    const text = tryRead(file)
    if (!text) {
      problems.push(`missing ${file}`)
      continue
    }
    for (const needle of needles) {
      if (needle && !text.includes(needle)) problems.push(`${file} does not mention ${needle}`)
    }
  }

  for (const file of HAND_WRITTEN) {
    if (!existsSync(join(root, file))) problems.push(`missing ${file}`)
  }

  for (const pkg of surface.packages) {
    const readme = join(root, pkg.dir, 'README.md')
    if (!existsSync(readme)) problems.push(`missing ${pkg.dir}/README.md`)
  }

  return problems
}

function write() {
  const surface = extract()
  writeFileSync(referencePath, generate(surface))
}

function check() {
  const surface = extract()
  const markdown = existsSync(referencePath) ? readFileSync(referencePath, 'utf8') : ''
  const problems = problemsFor(surface, markdown)
  if (problems.length) {
    console.error(problems.join('\n'))
    process.exit(1)
  }
}

const [command] = process.argv.slice(2)
if (command === 'write') {
  write()
} else if (command === 'check') {
  check()
} else if (command === 'json') {
  console.log(JSON.stringify(extract(), null, 2))
} else {
  console.error('usage: node scripts/docs.mjs write\n       node scripts/docs.mjs check\n       node scripts/docs.mjs json')
  process.exit(2)
}
